environmental <- c("I often choose methods of transportation that are friendlier to the environment",
                   "It is important to me that others see me as being environmentally conscious",
                   "I buy vehicles that reflect my commitment to support the environment",
                   "I feel I am more environmentally conscious than most people",
                   "I will go out of my way to buy a product that is environmentally safe",
                   "#I am more likely to buy a brand that is committed to reducing its impact on the environment",
                   "I buy natural products because I am concerned about the environment.",
                   "I feel helpless to make a change in the protection of the environment",
                   "I am willing to pay more for a product that is safe for the environment",
                   "When shopping for household cleaning products, I especially look for organic or natural products",
                   "People have a responsibility to use recycled products whenever possible",
                   "Any product that pollutes the environment should be banned",
                   "Owning a car is less important nowadays given the other options I have for getting around",
                   "I regularly eat organic foods",
                   "I try to buy foods that are grown or produced locally (in the region where I live)",
                   "Each of us has a personal obligation to do what we can to be environmentally responsible",
                   "A company's environmental record is important to me in my purchasing decisions",
                   "I buy products that use recycled paper in their packaging",
                   "I buy natural products because I am concerned about me and my family's health.",
                   "Climate change is a serious threat",
                   "I am interested in finding out how I can help the environment",
                   "My next car will be more eco-friendly",
                   "The government should pay more attention to environmental issues",
                   "People who are worried about the environment are overreacting",
                   "Climate change has become too political of a topic"
)

seeking_status <- c("I enjoy showing off my home to guests",
                    "I like to live a lifestyle that impresses others",
                    "My friends are the most important thing in my life",
                    "I like to give the impression that my life is under control",
                    "I buy vehicles that reflect my commitment to support the environment",
                    "In times of need I turn to my friends, not my family",
                    "It is important to me that others see me as being environmentally conscious",
                    "I feel I am more environmentally conscious than most people",
                    "I am as close to my friend group as I am to my family",
                    "It is important to look attractive to others",
                    "When I use social media, I only show my best self",
                    "I like other people to think I'm a financial success",
                    "My home is an expression of my personal style",
                    "It's important to me to feel respected by my peers",
                    "I enjoy being the center of attention",
                    "I strive to achieve a high social status",
                    "I would pay extra for a product that is consistent with the image I want to convey.",
                    "I want people I know to think of me as fashionable",
                    "I like to stand out in a crowd",
                    "I enjoy being the center of attention",
                    "I want to be more like the social media influencers I follow",
                    "I strive to achieve a high social status",
                    "I like to show off what I have",
                    "I'm willing to spend more for a quality bottle of wine",
                    "I must admit I wear designer brands partially to impress other people.",
                    "Social media is a way for me to tell people about companies and products I like",
                    "Social media improves my life overall",
                    "I like to create videos and other content to share on social media",
                    "I am more likely to purchase products I see, used or recommended by friends on social media",
                    "I expect most people to pay attention to my needs",
                    "I must admit I feel jealous of people I follow on social media",
                    "I like to keep up with the latest fashions",
                    "People often copy what I do or wear",
                    "My friend's opinion of a store influences whether I shop there",
                    "I am influenced by what's hot and what's not.",
                    "I like to post updates about my life on social media",
                    "EGOCENTRIC-vain, self-centered",
                    "I thrive at big parties and social occasions",
                    "I have a better fashion sense than most people",
                    "DOMINATING-controlling, aggressive",
                    "I would consider having a cosmetic surgery or procedure to improve my appearance",
                    "TENSE-nervous, high-strung",
                    "I like to introduce people to each other",
                    "I feel it is important to share my opinion")

culturally_interested <- c("I am very interested in the fine arts",
                           "TV is more interesting now than ever before",
                           "It is important for companies to create advertising that is culturally diverse in order to stay relevant",
                           "I like to learn about foreign cultures",
                           "Living in a foreign country is something I would like to experience",
                           "Traveling to foreign places is a great way for me to learn about other cultures.",
                           "I often talk about TV shows with my friends",
                           "I often talk about things I see on social media with others",
                           "I enjoy eating foods from different cultures",
                           "To me, it is important to keep up-to-date with news and current affairs",
                           "I subscribe to streaming services just for the original programming",
                           "Vacation is a time for me to meet new people",
                           "I like to try local cuisine when I travel.",
                           "For me, going out to eat is all about the \"experience\"",
                           "INTELLIGENT-smart, well-informed")

open_minded_curious <- c("I like to learn about foreign cultures",
                         "I like to challenge myself by doing new things",
                         "Living in a foreign country is something I would like to experience",
                         "I'm interested in learning about things just for fun",
                         "I am interested in how the universe works",
                         "BROAD-MINDED-open-minded, tolerant",
                         "Marijuana should be legalized",
                         "I am an optimist")

religious_faith <- c("I attend religious services regularly",
                     "Prayer is a part of my daily life",
                     "Religion should be the pillar of our society",
                     "I consider myself a spiritual person",
                     "I believe in the biblical teaching that God created the world in six days",
                     "The government should support prayer in school",
                     "Worrying about the future is a waste of time",
                     "People who overanalyze are annoying")

conservative <- c("I always do what my doctor tells me to do",
                  "I am perfectly happy with my standard of living",
                  "I feel financially secure",
                  "When it comes to homeowners or renters' insurance, I make sure I am well-insured by having all the coverage I need",
                  "Keeping a neat, organized home is a top priority for me",
                  "I enjoy maintaining traditions",
                  "I'm more connected to my ethnic heritage than my parents are",
                  "I take an active role in planning for my retirement",
                  "I always maintain my vehicle as recommended by the manufacturer's manual",
                  "I just want to use my cell phone for basic communication and don't care about the other features",
                  "It is important for me to go to the doctor when I'm sick",
                  "I am confident negotiating with automotive salespeople",
                  "When it comes to life insurance, I make sure I am well-insured by having all the coverage I need",
                  "There is too much emphasis on sex in today's culture",
                  "Buying American products is important to me.",
                  "I'd rather prepare a meal than eat at a restaurant",
                  "I make an extra effort to have my house smell fresh",
                  "Financial security after retirement is the responsibility of each individual",
                  "I'm careful with my money",
                  "To use a new technology product, someone has to show me how",
                  "My cultural/ethnic heritage is an important part of who I am",
                  "I go to the doctor regularly for check-ups",
                  "I frequently take preventative medicine",
                  "I clear my browsing history regularly out of concern for my privacy",
                  "People who are worried about the environment are overreacting",
                  "I'd rather travel in the U.S. than to a foreign location.",
                  "In general, I know my credit score",
                  "I always know broadly how much is in my bank account at any one time.",
                  "It is better for me to put my money in a low-risk investment, even if the return may not be as great.",
                  "Dinners in my home are usually planned ahead of time",
                  "I decide what I want before I go shopping",
                  "Climate change has become too political of a topic",
                  "People who overanalyze are annoying",
                  "Kids today are permitted too much screen-time",
                  "I prefer a store that has a large selection of familiar brands.",
                  "It's important to me that my children continue my family's cultural traditions",
                  "When choosing a hotel, I consider its safety and hygiene practices, along with the other amenities offered",
                  "I am concerned about credit card identity theft",
                  "I prefer road trips over trips that require a flight",
                  "I buy the brands I grew up with, the ones my parents used.",
                  "People need more vitamins as they get older",
                  "Video telemedicine appointments with a doctor seem too impersonal",
                  "I prefer to pay cash for things I buy, whenever I can")

seeking_adventure_risk <- c(
  "I enjoy taking risks",
  "I like to challenge myself by doing new things",
  "I like to take risks when investing for the chance of a high return.",
  "I consider myself a thrill seeker",
  "I seek adventure and thrills on my vacations",
  "I like to experiment with new clothing styles",
  "I enjoy experimenting with haircare and styling products I've never used before.",
  "I often try different ways to style my hair.",
  "I often desire excitement in my life",
  "I like to try new recipes when I entertain",
  "I enjoy eating foods from different cultures",
  "I prefer foods cooked with bold flavors",
  "For me, going out to eat is all about the \"experience\"",
  "I like to learn about foreign cultures",
  "My philosophy is \"Life should be as much fun as possible\"",
  "I seek out variety in my everyday life",
  "I frequently look for new ways to change up my exercise routine",
  "BRAVE-courageous, daring",
  "On my vacations, I prefer traveling to places I've never been.",
  "I frequently choose active vacations with lots to do.",
  "Travel is one of my passions",
  "When traveling, I like to be spontaneous",
  "I often do things on the spur of the moment",
  "I often desire excitement in my life",
  "I like to challenge myself by doing new things",
  "I consider myself a thrill seeker",
  "Living in a foreign country is something I would like to experience",
  "I'm interested in learning about things just for fun")

family_oriented <- c("Spending time with my family is my top priority",
                     "I must admit, I work most weekends",
                     "I am willing to sacrifice time with my family in order to get ahead",
                     "My children have a significant impact on the brands I choose.",
                     "I enjoy watching kids' TV shows with my children",
                     "I frequently wish I had more time to spend with my family",
                     "My spouse has a significant impact on the brands I choose.",
                     "I use food to bring family together",
                     "Juggling family and work demands is very stressful for me",
                     "I think it is good for parents to provide children with more things than they had",
                     "I like watching TV together with my friends and family")

gaming <- c("I play video games enough to consider myself a 'gamer'",
            "I spend more money on video games than I do on other forms of entertainment",
            "I find video games to be more entertaining than television",
            "Video games are my main source of entertainment")

impulsive_shortterm <- c("Fast food fits my busy lifestyle",
                         "I often feel like my life is slipping out of control",
                         "Juggling family and work demands is very stressful for me",
                         "I tend to make impulse purchases.",
                         "I work primarily for the salary",
                         "Because of my busy lifestyle, I don't take care of myself as well as I should",
                         "TENSE-nervous, high-strung",
                         "I'm a \"spender\" rather than a \"saver\".",
                         "I feel compelled to check my phone, even when I'm in the middle of a conversation",
                         "I am so busy, I often can't finish everything I need to in a day",
                         "I tend to spend money without thinking",
                         "I prefer picking up quick meals to cooking meals",
                         "When I eat out, I like to splurge on unhealthy foods",
                         "I worry about being able to retire when I want to",
                         "AWKWARD-shy, bashful",
                         "FORGETFUL-careless, absent-minded",
                         "I use my cell phone to research where to go or what to do in my free time",
                         "My cell phone makes it harder for me to concentrate at work",
                         "I often eat frozen dinners",
                         "Often I buy clothes that I don't really need",
                         "To me, financial planning feels like a complicated task")

tech_forward <- c("The Internet has become a primary source of entertainment for me",
                  "My cell phone is an extension of my personality",
                  "I use my cell phone to research where to go or what to do in my free time",
                  "I want others to say \"wow\" when they see my electronics",
                  "People often ask my opinion when they are buying new technology",
                  "My computer is a primary source of fun and entertainment",
                  "My friends often ask for my advice before buying electronic equipment",
                  "I like to have a lot of gadgets",
                  "I would feel disconnected without the Internet",
                  "I text more than I talk on my phone",
                  "I am more likely to purchase a product online than in a store",
                  "When I need to solve a problem, I search online for what to do",
                  "My mobile device provides entertainment during my daily commute",
                  "Apps have made my life so much more convenient",
                  "I rely on the Internet to communicate with friends and family",
                  "Checking my cell phone is the first thing I do in the morning",
                  "I rely on my cell phone to keep up with news or sports" ,
                  "My cell phone connects me to my social world",
                  "It's important for me to have Internet access when I am 'on-the-go' -- away from home or work",
                  "When I need information the first place I look is the Internet",
                  "When I need to solve a problem, I ask people online what they would do",
                  "I rely on a mobile app to keep track of my fitness habits")

work <- c("I must admit, I work most weekends",
          "I am a workaholic",
          "I am so busy, I often can't finish everything I need to in a day",
          "I am willing to sacrifice time with my family in order to get ahead",
          "I would continue working even if I won the lottery",
          "My goal is to make it to the top of my profession",
          "I would like to set up my own business one day",
          "When I am sick, I still drag myself to work",
          "I Consider My Work To Be A Career, Not Just A Job",
          "To me, it's important to always be reachable wherever I am")

shopping_penny_pincher <- c("Price is more important to me than brand names.",
                            "My number one goal when shopping is to save as much money as possible.",
                            "I will gladly switch brands to use a coupon.",
                            "I smell personal care and household products in the store before I buy them.",
                            "I often save money by buying previously used items",
                            "I usually only shop at my favorite stores because they have the prices I like",
                            "Generic or store brand products are as effective as brand-name products.",
                            "If generic brands are on sale, I will purchase them over my normal name-brand",
                            "I shop around a lot to take advantage of specials or bargains",
                            "I'll shop at stores I don't normally shop at to check out a sale",
                            "I tend to hold off on buying things I want until they go on sale",
                            "In general, price is more important to me than convenience when making travel plans",
                            "I want the cheapest to maintain vehicle I can find",
                            "I would buy eco-friendly products if they were less expensive",
                            "Travel and hotel discounts have a strong influence on where I choose to travel and where I choose to stay.",
                            "I like to compare prices across different sites before purchasing something online.",
                            "When shopping online I always search for a discount code before making a purchase",
                            "Investing in the stock market is too risky for me.",
                            "The offer of \"free shipping\" attracts me to a shopping website",
                            "I prefer to shop at stores that offer loyalty rewards",
                            "I feel overwhelmed by financial burdens.",
                            "Often I can be swayed by coupons to try new food products",
                            "I hold off on making big purchases until after I get my tax refund",
                            "A used car is just as good as a new car",
                            "If I find something I want in a store, I go online to see if I can find a better deal",
                            "Last-minute travel specials are a great way to get a bargain",
                            "I rely on mobile coupons for deals while food shopping",
                            "I struggle to pay the costs of health care")

shopping_purposeful_shoppers <- c("#I am more likely to buy a brand that is committed to reducing its impact on the environment",
                                  "I buy brands that reflect my style.",
                                  "I am willing to pay more for a product that is safe for the environment",
                                  "I buy natural products because I am concerned about me and my family's health.",
                                  "I actively seek information about nutrition and healthy diet",
                                  "I usually read the information on product labels",
                                  "I like to read reviews before buying technology or electronics.",
                                  "Before purchasing a product online, I typically read online reviews submitted by others.",
                                  "Before buying electronics, I do as much research as possible.",
                                  "When shopping for household cleaning products, I especially look for organic or natural products",
                                  "I buy natural products because I am concerned about the environment.",
                                  "I enjoy learning about technology or electronic products from others",
                                  "I often use natural or organic beauty products",
                                  "I'm willing to spend more for a quality bottle of wine",
                                  "I like to buy technology products which easily connect to products that I already have",
                                  "I would pay extra for a product that is consistent with the image I want to convey.",
                                  "I buy products that use recycled paper in their packaging",
                                  "I purchase products to help organize my life",
                                  "I'm willing to pay more for a food product that treats animals ethically and humanely",
                                  "A company's environmental record is important to me in my purchasing decisions",
                                  "I prefer to buy products that offer the latest in new technology.",
                                  "I am more likely to purchase brands that support a cause I care about.",
                                  "Nutritional value is the most important factor when I'm choosing which foods to eat",
                                  "I always check ingredients and nutritional content on the labels of products before I buy them",
                                  "It's worth it to me to pay more for high quality hotel accommodations",
                                  "I expect the brands I buy to support social causes.",
                                  "I buy based on quality, not price.",
                                  "I love doing research on a location before I go on vacation.",
                                  "I am willing to pay more for a flight in order to travel on my favorite airline.",
                                  "I would pay extra for a product that is consistent with the image I want to convey.")

shopping_only_the_best <- c("I'm willing to pay more for top quality electronics.",
                            "I buy based on quality, not price.",
                            "Getting exactly what I want is more important than the price of an item",
                            "If a product is made by a company I trust, I'll buy it even if it is slightly more expensive.",
                            "I'm willing to spend more for a quality bottle of wine",
                            "I normally buy cars brand new",
                            "My spouse has a significant impact on the brands I choose.",
                            "I am willing to pay extra for prescription drugs not covered by health insurance",
                            "I would be comfortable buying a \"big ticket\" item, like a car or appliance, completely online",
                            "I prefer to buy products that offer the latest in new technology.",
                            "I am willing to pay more for a product that is safe for the environment",
                            "I regularly eat organic foods",
                            "My budget allows for me to buy expensive designer clothes",
                            "I typically drink wine with dinner",
                            "I prefer purchasing things online for a fixed price,as opposed to bidding in online auctions",
                            "I prefer shopping at specialty stores because the employees are knowledgeable about products",
                            "I am among the first of my friends and colleagues to try new technology products.",
                            "When shopping for household cleaning products, I especially look for organic or natural products")

shopping_impulsive_and_influenced <- c("When a celebrity designs a product, I am more likely to buy it.",
                                       "A celebrity endorsement may motivate me to buy a product",
                                       "I prefer to buy things my friends or neighbors would approve of.",
                                       "Seeing a celebrity using a product may influence me to buy it",
                                       "I will spend whatever I have to, to make myself look younger",
                                       "I am influenced by what's hot and what's not.",
                                       "A designer label improves a person's image",
                                       "I am more likely to buy products from companies that sponsor sports teams and sports events",
                                       "Social media influencers impact the brands I buy",
                                       "I always upgrade to a new cell phone as soon as the latest model is released",
                                       "I must admit I wear designer brands partially to impress other people.",
                                       "I'll try any new diet",
                                       "I'm always checking out the app store to see what's new",
                                       "I'm always one of the first of my friends to try new products or services.",
                                       "I like to change brands often for the sake of variety and novelty.",
                                       "My friend's opinion of a store influences whether I shop there",
                                       "I am usually the first among my friends to try new clothing styles",
                                       "I am willing to spend more than I can really afford, to get the clothes that I want",
                                       "I am likely to purchase products I see advertised on my cell phone",
                                       "I follow influencers on social media for tips on fashion and beauty",
                                       "EGOCENTRIC-vain, self-centered",
                                       "I'll pay just about anything for an electronic product that I really want",
                                       "Posts I see on social media influence my fashion choices",
                                       "I am more likely to purchase products I see advertised on social media")

loyalty <- c("I will gladly switch brands to use a coupon.",
             "If generic brands are on sale, I will purchase them over my normal name-brand",
             "I'll shop at stores I don't normally shop at to check out a sale",
             "I prefer to shop at stores that offer loyalty rewards",
             "If a product is made by a company I trust, I'll buy it even if it is slightly more expensive.",
             "Buying American products is important to me.",
             "I eat the foods I like regardless of calories",
             "I usually only shop at my favorite stores because I know they have the brands I like",
             "I am more likely to switch cell phone service providers if they offer the latest in technology",
             "I am willing to pay more for a flight in order to travel on my favorite airline.",
             "Brand name is the best indication of quality.",
             "I like to change brands often for the sake of variety and novelty.")

active_humanitarian <- c("I often volunteer my time for a good cause",
                         "I use social media to support causes I care about",
                         "If I feel strongly about an issue, I will participate in a civil protest",
                         "I like to introduce people to each other",
                         "My friends and acquaintances look to me to organize our activities",
                         "I often find myself in a leadership position",
                         "I am interested in finding out how I can help the environment",
                         "A company's environmental record is important to me in my purchasing decisions",
                         "I expect the brands I buy to support social causes.",
                         "I am more likely to purchase brands that support a cause I care about.",
                         "I'm good at convincing others to try new things",
                         "I typically use skincare products that contain sunscreen.",
                         "It is important for companies to create advertising that is culturally diverse in order to stay relevant",
                         "I consider myself a born leader",
                         "The government should pay more attention to environmental issues",
                         "EFFICIENT-organized, thorough",
                         "GENEROUS-giving, unselfish",
                         "I am willing to take charge to get things done")

performative_progressive <- c("I buy vehicles that reflect my commitment to support the environment",
                              "#I am more likely to buy a brand that is committed to reducing its impact on the environment",
                              "A company's environmental record is important to me in my purchasing decisions",
                              "I buy products that use recycled paper in their packaging",
                              "My next car will be more eco-friendly",
                              "I am willing to pay more for a product that is safe for the environment",
                              "I am interested in finding out how I can help the environment",
                              "If I feel strongly about an issue, I will participate in a civil protest",
                              "When shopping for household cleaning products, I especially look for organic or natural products",
                              "I feel I am more environmentally conscious than most people",
                              "I regularly eat organic foods",
                              "I will go out of my way to buy a product that is environmentally safe",
                              "It is important to me that others see me as being environmentally conscious",
                              "I buy natural products because I am concerned about the environment.",
                              "I prefer shopping at local, independent stores to shopping at national store chains",
                              "I am more likely to purchase brands that support a cause I care about.",
                              "I try to buy foods that are grown or produced locally (in the region where I live)",
                              "I'm willing to pay more for a food product that treats animals ethically and humanely",
                              "I buy natural products because I am concerned about me and my family's health.",
                              "I expect the brands I buy to support social causes.")

first_mover <- c("I am usually the first among my friends to try new food products",
                 "I am among the first of my friends and colleagues to try new technology products.",
                 "I'm always one of the first of my friends to try new products or services.",
                 "I am usually the first among my friends to try new clothing styles",
                 "I'm often first to try the most advanced medicines")

influencer <- c("My friends often ask for my advice before buying electronic equipment",
                "People come to me for advice before buying new things",
                "When I find a technology or electronic product I like, I typically recommend it to people I know.",
                "I'm good at convincing others to try new things",
                "People often copy what I do or wear",
                "I like to share my opinions about products and services by posting reviews and ratings online.",
                "People often ask my advice when it comes to automobiles",
                "People often ask my advice when it comes to vacation travel.",
                "People often ask my advice when it comes to financial matters.",
                "My friends and acquaintances look to me to organize our activities",
                "People often ask my opinion when they are buying new technology",
                "I often take the opportunity to discuss my knowledge of financial products or services with others",
                "I'm always one of the first of my friends to try new products or services.",
                "I'm good at convincing others to try new things")

influenced <-  c("I like watching shows that everyone's talking about",
                 "Posts I see on social media influence my fashion choices",
                 "I like to follow my favorite brands or companies on social media",
                 "Social media influencers impact the brands I buy",
                 "I follow influencers on social media for tips on fashion and beauty",
                 "I look to social media for tips on how to do my makeup",
                 "When I need to solve a problem, I ask people online what they would do",
                 "I often seek advice from others when it comes to making purchase decisions",
                 "My purchase decisions are influenced by the latest health food trends",
                 "I am influenced by what's hot and what's not.",
                 "I take advice on health issues from my friends",
                 "I am more likely to purchase products I see, used or recommended by friends on social media",
                 "Celebrity chefs inspire me to cook/bake")

privacy_diligent <- c("I often research a company or organization online before I give them information about myself",
                      "I often read the privacy statements that companies have on their website or in print",
                      "I clear my browsing history regularly out of concern for my privacy",
                      "I feel like I have control over what can be found about me online.",
                      "I like knowing how companies are using information about me",
                      "Most of the personal information about me that is online is relatively harmless")

privacy_willing <- c("I'm OK with companies using personal information about me to better understand products and services I might want.",
                     "I trust the federal government to make the best decisions about how to protect my privacy",
                     "I am willing to provide some personal information to a company in order to get something that I want")

privacy_anxious <- c("I worry that \"smart\" home devices/appliances could invade my privacy",
                     "Once a piece of personal information becomes available online, there is nothing I can do about it.",
                     "I often wish I could take a break from technology",
                     "I have experienced a situation where online information about me has had negative consequences",
                     "I think people put too much private information on the Internet",
                     "I like knowing how companies are using information about me")

fashionista <- c("I like to make a unique fashion statement",
                 "I love to mix and match high and low end designers when putting together an outfit.",
                 "I want people I know to think of me as fashionable",
                 "I like to experiment with new clothing styles",
                 "I have a better fashion sense than most people",
                 "I am usually the first among my friends to try new clothing styles",
                 "I consider my fashion style to be trendy.",
                 "I often try different ways to style my hair.",
                 "Buying new clothes gives me a thrill.",
                 "People often copy what I do or wear",
                 "I purchase clothes that make me feel confident.",
                 "I enjoy experimenting with haircare and styling products I've never used before.",
                 "I like to keep up with the latest fashions",
                 "I consider my fashion style to be trendy.")

money_materialistic <- c("I like other people to think I'm a financial success",
                         "Money is the best measure of success",
                         "I want people I know to think of me as fashionable",
                         "My goal is to make it to the top of my profession",
                         "I am willing to sacrifice time with my family in order to get ahead",
                         "People often copy what I do or wear",
                         "I judge others by how \"put together\" they look.",
                         "I prefer driving a luxury vehicle",
                         "I expect most people to pay attention to my needs",
                         "It is important to look attractive to others",
                         "I enjoy learning about financial products or services from others",
                         "I often take the opportunity to discuss my knowledge of financial products or services with others",
                         "I want others to say \"wow\" when they see my electronics",
                         "I prefer to buy products that offer the latest in new technology.",
                         "Maintaining a youthful appearance is important to me",
                         "I like to take risks when investing for the chance of a high return.",
                         "The technologies offered in a car's dashboard influence my decision to buy it",
                         "DOMINATING-controlling, aggressive",
                         "#I think it is good for parents to provide children with more things than they had",
                         "I enjoy showing off my home to guests",
                         "I'm willing to pay more for top quality electronics.",
                         "My budget allows for me to buy expensive designer clothes")

ambitious <- c("My goal is to make it to the top of my profession",
               "I consider myself a thrill seeker",
               "People often copy what I do or wear",
               "I want people I know to think of me as fashionable",
               "I like other people to think I'm a financial success",
               "I am willing to sacrifice time with my family in order to get ahead",
               "Money is the best measure of success" ,
               "I would like to set up my own business one day" ,
               "I often desire excitement in my life",
               "I enjoy taking risks",
               "I'm good at convincing others to try new things",
               "I am a workaholic",
               "I expect most people to pay attention to my needs",
               "I consider myself a born leader",
               "I often find myself in a leadership position",
               "I seek out variety in my everyday life",
               "DOMINATING-controlling, aggressive",
               "I would pay extra for a product that is consistent with the image I want to convey.",
               "I Consider My Work To Be A Career, Not Just A Job",
               "REFINED-sophisticated, polished",
               "I thrive at big parties and social occasions",
               "I like to challenge myself by doing new things",
               "BRAVE-courageous, daring",
               "On the whole, people get what they deserve in life",
               "I purchase clothes that make me feel confident.",
               "It is important to look attractive to others",
               "I am so busy, I often can't finish everything I need to in a day",
               "I enjoy showing off my home to guests",
               "I must admit, I work most weekends",
               "I would continue working even if I won the lottery",
               "Juggling family and work demands is very stressful for me",
               "I am willing to take charge to get things done",
               "It's important to me to feel respected by my peers",
               "I frequently look for new ways to change up my exercise routine",
               "I am more capable than most people",
               "I feel it is important to share my opinion",
               "I am more capable than most people")

creative <- c("CREATIVE-imaginative, artistic",
              "I am very interested in the fine arts",
              "I like to make a unique fashion statement",
              "I like to challenge myself by doing new things",
              "I like to experiment with new clothing styles",
              "I seek out variety in my everyday life",
              "I prefer to make something rather than buy it",
              "I like to introduce people to each other",
              "I enjoy taking risks",
              "I consider myself a thrill seeker",
              "I often try different ways to style my hair.",
              "I like to learn about foreign cultures",
              "Vacation is a time for me to meet new people",
              "I often desire excitement in my life",
              "I enjoy DIY (do it yourself) projects",
              "I'm interested in learning about things just for fun",
              "I enjoy being creative in the kitchen",
              "Living in a foreign country is something I would like to experience",
              "BROAD-MINDED-open-minded, tolerant")

feeling_young <- c("Being able to customize an item makes me more willing to purchase it.",
                   "Maintaining a youthful appearance is important to me",
                   "It is important to look attractive to others",
                   "My philosophy is \"Life should be as much fun as possible\"",
                   "I feel really good about seeing celebrities in the media that share my ethnic background",
                   "I seek out variety in my everyday life",
                   "My cultural/ethnic heritage is an important part of who I am",
                   "I'll pay just about anything when it concerns my health",
                   "BRAVE-courageous, daring",
                   "REFINED-sophisticated, polished",
                   "I'm always looking for new ideas to improve my home",
                   "I often desire excitement in my life")

societal_conformity <- c("I always follow the advice of my mechanic",
                         "I always maintain my vehicle as recommended by the manufacturer's manual",
                         "Comfort is the most important thing in a car",
                         "I think shopping is a great way to relax.",
                         "I usually like to wait until other people have tried things before I try them myself.",
                         "I prefer to shop at stores that offer loyalty rewards",
                         "I am content with my appearance.",
                         "Investing in the stock market is too risky for me.",
                         "The economy has a direct effect on my spending habits",
                         "I am concerned about credit card identity theft",
                         "When it comes to life insurance, I make sure I am well-insured by having all the coverage I need",
                         "Eating fattening foods makes me feel guilty",
                         "Often I can be swayed by coupons to try new food products",
                         "I often read the recipes that come with products that I buy",
                         "Prayer is a part of my daily life",
                         "Keeping a neat, organized home is a top priority for me",
                         "My philosophy is \"Life should be as much fun as possible\"",
                         "It's important to me that my children continue my family's cultural traditions",
                         "My cultural/ethnic heritage is an important part of who I am",
                         "I Avoid confrontation whenever possible",
                         "I enjoy maintaining traditions",
                         "I make an extra effort to have my house smell fresh",
                         "I like to buy gifts as a way of expressing gratitude",
                         "I think it is good for parents to provide children with more things than they had",
                         "People need more vitamins as they get older",
                         "I appreciate hearing stories of people who suffer from my health condition(s)",
                         "It is important for me to go to the doctor when I'm sick",
                         "#I am a lot more cautious in what I do and how I do it since COVID-19",
                         "#I often look for products or services that can help improve my overall mental well-being",
                         "#Taking care of your mental health is a critical part of your overall wellness",
                         "SOCIABLE-friendly, likeable",
                         "I often research a company or organization online before I give them information about myself",
                         "On my vacations, I prefer traveling to places I've never been.",
                         "Packaged deals are great, because I don't have to plan out the details too much.",
                         "When I find a vacation spot I like, I go back whenever I can.",
                         "I prefer a vacation where activities are organized for me",
                         "I'm always looking for new ideas to improve my home",
                         "I worry about violence and crime",
                         "I believe in the biblical teaching that God created the world in six days",
                         "The government should support prayer in school",
                         "Any product that pollutes the environment should be banned",
                         "I always do what my doctor tells me to do")

seeking_security <- c("The economy has a direct effect on my spending habits",
                      "#I have concerns over the security of online/digital banking",
                      "#I am a lot more cautious in what I do and how I do it since COVID-19",
                      "#I often look for products or services that can help improve my overall mental well-being",
                      "#Taking care of your mental health is a critical part of your overall wellness",
                      "I worry about violence and crime")

equality_opportunity <- c("It is important for companies to create advertising that is culturally diverse in order to stay relevant",
                          "The government should pay more attention to environmental issues",
                          "Climate change is a serious threat",
                          "I like to learn about foreign cultures",
                          "People have a responsibility to use recycled products whenever possible",
                          "My cultural/ethnic heritage is an important part of who I am",
                          "Each of us has a personal obligation to do what we can to be environmentally responsible",
                          "BROAD-MINDED-open-minded, tolerant",
                          "Social media platforms have a responsibility to monitor what people post",
                          "Any product that pollutes the environment should be banned")

good_appearances <- c(
  "My first consideration in choosing a vehicle is its exterior styling",
  "My car should express my personality",
  "I buy brands that reflect my style.",
  "Being able to customize an item makes me more willing to purchase it.",
  "I often spend more money than I expected to on my fashion purchases.",
  "I follow a strict skin-care routine.",
  "You can tell a lot about a person by the clothes they wear.",
  "I would consider having a cosmetic surgery or procedure to improve my appearance",
  "Maintaining a youthful appearance is important to me",
  "I purchase clothes that make me feel confident.",
  "It is important to look attractive to others",
  "Buying new clothes gives me a thrill.",
  "Keeping a neat, organized home is a top priority for me",
  "My home is an expression of my personal style",
  "I make an extra effort to have my house smell fresh",
  "I like to buy gifts as a way of expressing gratitude",
  "It's important to me to feel respected by my peers",
  "I am always looking for new ways to live a healthier life",
  "REFINED-sophisticated, polished",
  "It's worth it to me to pay more for high quality hotel accommodations",
  "I'm willing to spend more for a quality bottle of wine",
  "I'm always looking for new ideas to improve my home"
)

## add health / wellness

saveRDS(
  object = list(
    active_humanitarian = active_humanitarian, ambitious = ambitious,
    conservative=conservative, creative=creative, culturally_interested=culturally_interested,
    environmental=environmental, equality_opportunity=equality_opportunity,
    family_oriented=family_oriented, fashionista=fashionista, feeling_young=feeling_young,
    first_mover=first_mover, gaming=gaming, good_appearances=good_appearances,
    impulsive_shortterm=impulsive_shortterm, influenced=influenced, influencer=influencer,
    loyalty=loyalty, money_materialistic=money_materialistic,
    open_minded_curious=open_minded_curious, performative_progressive=performative_progressive,
    privacy_anxious=privacy_anxious,
    privacy_diligent=privacy_diligent, privacy_willing=privacy_willing,
    religious_faith=religious_faith, seeking_adventure_risk=seeking_adventure_risk,
    seeking_security=seeking_security, seeking_status=seeking_status,
    shopping_impulsive_and_influenced=shopping_impulsive_and_influenced,
    shopping_only_the_best=shopping_only_the_best, shopping_penny_pincher=shopping_penny_pincher,
    shopping_purposeful_shoppers=shopping_purposeful_shoppers, societal_conformity=societal_conformity,
    tech_forward=tech_forward, work=work
  ),
  file = here::here("data", "all_simmons_segments.rds"))








